use library;

db.books.insertMany([
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0743273565',
    publishedYear: 1925,
    genre: 'Fiction',
    availableCopies: 2,
    totalCopies: 5,
    borrowHistory: [
      {
        borrowerName: 'John Smith',
        borrowDate: new Date('2024-01-15'),
        returnDate: new Date('2024-02-01'),
        status: 'returned',
      },
      {
        borrowerName: 'Emma Johnson',
        borrowDate: new Date('2024-02-10'),
        returnDate: new Date('2024-02-25'),
        status: 'returned',
      },
      {
        borrowerName: 'Michael Brown',
        borrowDate: new Date('2024-11-01'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Sarah Davis',
        borrowDate: new Date('2024-11-15'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'David Wilson',
        borrowDate: new Date('2024-12-01'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review:
          'A masterpiece of American literature. The prose is beautiful and the story is timeless.',
        reviewDate: new Date('2024-02-05'),
      },
      {
        rating: 4,
        review: 'Great book, though the ending left me wanting more.',
        reviewDate: new Date('2024-02-28'),
      },
    ],
    addedDate: new Date('2023-12-01'),
  },
  {
    title: '1984',
    author: 'George Orwell',
    isbn: '978-0451524935',
    publishedYear: 1949,
    genre: 'Science Fiction',
    availableCopies: 1,
    totalCopies: 3,
    borrowHistory: [
      {
        borrowerName: 'Alex Turner',
        borrowDate: new Date('2024-03-10'),
        returnDate: new Date('2024-03-24'),
        status: 'returned',
      },
      {
        borrowerName: 'Lisa Anderson',
        borrowDate: new Date('2024-10-05'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Robert Taylor',
        borrowDate: new Date('2024-11-20'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'Chillingly relevant even today. A must-read.',
        reviewDate: new Date('2024-03-25'),
      },
      {
        rating: 5,
        review: "Orwell's vision is terrifying and prophetic.",
        reviewDate: new Date('2024-04-12'),
      },
      {
        rating: 4,
        review: 'Dark and thought-provoking.',
        reviewDate: new Date('2024-05-01'),
      },
    ],
    addedDate: new Date('2023-12-01'),
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '978-0061120084',
    publishedYear: 1960,
    genre: 'Fiction',
    availableCopies: 3,
    totalCopies: 4,
    borrowHistory: [
      {
        borrowerName: 'Jennifer White',
        borrowDate: new Date('2024-04-01'),
        returnDate: new Date('2024-04-20'),
        status: 'returned',
      },
      {
        borrowerName: 'Chris Martinez',
        borrowDate: new Date('2024-12-05'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'A powerful story about justice and morality. Unforgettable characters.',
        reviewDate: new Date('2024-04-22'),
      },
      {
        rating: 5,
        review: 'This book should be required reading for everyone.',
        reviewDate: new Date('2024-05-15'),
      },
    ],
    addedDate: new Date('2023-12-15'),
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    isbn: '978-0547928227',
    publishedYear: 1937,
    genre: 'Fantasy',
    availableCopies: 0,
    totalCopies: 4,
    borrowHistory: [
      {
        borrowerName: 'Tom Harris',
        borrowDate: new Date('2024-05-10'),
        returnDate: new Date('2024-06-01'),
        status: 'returned',
      },
      {
        borrowerName: 'Amy Clark',
        borrowDate: new Date('2024-11-01'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Kevin Lewis',
        borrowDate: new Date('2024-11-10'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Nancy Walker',
        borrowDate: new Date('2024-11-25'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Paul Hall',
        borrowDate: new Date('2024-12-01'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'An enchanting adventure that sparked my love for fantasy.',
        reviewDate: new Date('2024-06-05'),
      },
      {
        rating: 4,
        review: 'Wonderful world-building and memorable characters.',
        reviewDate: new Date('2024-07-20'),
      },
    ],
    addedDate: new Date('2024-01-10'),
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '978-0141439518',
    publishedYear: 1813,
    genre: 'Romance',
    availableCopies: 2,
    totalCopies: 3,
    borrowHistory: [
      {
        borrowerName: 'Elizabeth Green',
        borrowDate: new Date('2024-06-15'),
        returnDate: new Date('2024-07-05'),
        status: 'returned',
      },
      {
        borrowerName: 'Maria Rodriguez',
        borrowDate: new Date('2024-12-10'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'Witty, romantic, and absolutely delightful. Austen at her best.',
        reviewDate: new Date('2024-07-08'),
      },
      {
        rating: 4,
        review: 'A classic romance with great character development.',
        reviewDate: new Date('2024-08-12'),
      },
      {
        rating: 5,
        review: "I've read this three times and it never gets old!",
        reviewDate: new Date('2024-09-01'),
      },
    ],
    addedDate: new Date('2024-01-15'),
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    isbn: '978-0316769488',
    publishedYear: 1951,
    genre: 'Fiction',
    availableCopies: 4,
    totalCopies: 5,
    borrowHistory: [
      {
        borrowerName: 'Brian King',
        borrowDate: new Date('2024-07-01'),
        returnDate: new Date('2024-07-20'),
        status: 'returned',
      },
      {
        borrowerName: 'Susan Wright',
        borrowDate: new Date('2024-11-28'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 3,
        review: 'Interesting perspective but Holden can be frustrating at times.',
        reviewDate: new Date('2024-07-25'),
      },
      {
        rating: 4,
        review: 'A raw and honest portrayal of teenage angst.',
        reviewDate: new Date('2024-08-15'),
      },
    ],
    addedDate: new Date('2024-02-01'),
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    isbn: '978-0439708180',
    publishedYear: 1997,
    genre: 'Fantasy',
    availableCopies: 1,
    totalCopies: 6,
    borrowHistory: [
      {
        borrowerName: 'Oliver Scott',
        borrowDate: new Date('2024-08-01'),
        returnDate: new Date('2024-08-15'),
        status: 'returned',
      },
      {
        borrowerName: 'Sophie Turner',
        borrowDate: new Date('2024-09-10'),
        returnDate: new Date('2024-09-25'),
        status: 'returned',
      },
      {
        borrowerName: 'Daniel Adams',
        borrowDate: new Date('2024-10-01'),
        returnDate: new Date('2024-10-20'),
        status: 'returned',
      },
      {
        borrowerName: 'Emma Baker',
        borrowDate: new Date('2024-11-05'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Lucas Mitchell',
        borrowDate: new Date('2024-11-18'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Olivia Carter',
        borrowDate: new Date('2024-12-01'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'James Phillips',
        borrowDate: new Date('2024-12-08'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Mia Evans',
        borrowDate: new Date('2024-12-12'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'The book that started it all! Pure magic.',
        reviewDate: new Date('2024-08-18'),
      },
      {
        rating: 5,
        review: 'Absolutely captivating from start to finish.',
        reviewDate: new Date('2024-09-28'),
      },
      {
        rating: 5,
        review: 'A magical journey that appeals to all ages.',
        reviewDate: new Date('2024-10-22'),
      },
      {
        rating: 4,
        review: 'Great start to an incredible series.',
        reviewDate: new Date('2024-11-01'),
      },
    ],
    addedDate: new Date('2024-02-15'),
  },
  {
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    isbn: '978-0307474278',
    publishedYear: 2003,
    genre: 'Thriller',
    availableCopies: 3,
    totalCopies: 4,
    borrowHistory: [
      {
        borrowerName: 'Richard Moore',
        borrowDate: new Date('2024-09-01'),
        returnDate: new Date('2024-09-18'),
        status: 'returned',
      },
      {
        borrowerName: 'Patricia Young',
        borrowDate: new Date('2024-12-05'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 4,
        review: 'A page-turner with fascinating historical elements.',
        reviewDate: new Date('2024-09-20'),
      },
      {
        rating: 3,
        review: 'Entertaining but historically questionable.',
        reviewDate: new Date('2024-10-15'),
      },
    ],
    addedDate: new Date('2024-03-01'),
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '978-0062315007',
    publishedYear: 1988,
    genre: 'Fiction',
    availableCopies: 2,
    totalCopies: 3,
    borrowHistory: [
      {
        borrowerName: 'William Hill',
        borrowDate: new Date('2024-10-01'),
        returnDate: new Date('2024-10-22'),
        status: 'returned',
      },
      {
        borrowerName: 'Jessica Lee',
        borrowDate: new Date('2024-12-03'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'Life-changing! A beautiful tale about following your dreams.',
        reviewDate: new Date('2024-10-25'),
      },
      {
        rating: 4,
        review: 'Philosophical and inspiring.',
        reviewDate: new Date('2024-11-10'),
      },
    ],
    addedDate: new Date('2024-03-15'),
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    isbn: '978-0307588371',
    publishedYear: 2012,
    genre: 'Thriller',
    availableCopies: 1,
    totalCopies: 3,
    borrowHistory: [
      {
        borrowerName: 'Andrew Nelson',
        borrowDate: new Date('2024-11-01'),
        returnDate: new Date('2024-11-15'),
        status: 'returned',
      },
      {
        borrowerName: 'Michelle Carter',
        borrowDate: new Date('2024-11-20'),
        returnDate: null,
        status: 'borrowed',
      },
      {
        borrowerName: 'Ryan Cooper',
        borrowDate: new Date('2024-12-01'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: "Twisted and unpredictable. Couldn't put it down!",
        reviewDate: new Date('2024-11-18'),
      },
      {
        rating: 4,
        review: 'Dark psychological thriller that keeps you guessing.',
        reviewDate: new Date('2024-12-01'),
      },
    ],
    addedDate: new Date('2024-04-01'),
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '978-0062316097',
    publishedYear: 2011,
    genre: 'Non-Fiction',
    availableCopies: 2,
    totalCopies: 3,
    borrowHistory: [
      {
        borrowerName: 'Thomas Reed',
        borrowDate: new Date('2024-11-10'),
        returnDate: new Date('2024-12-01'),
        status: 'returned',
      },
      {
        borrowerName: 'Karen Bailey',
        borrowDate: new Date('2024-12-10'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'Mind-blowing perspective on human history and evolution.',
        reviewDate: new Date('2024-12-03'),
      },
      {
        rating: 5,
        review: 'Fascinating and thought-provoking. Highly recommend!',
        reviewDate: new Date('2024-12-08'),
      },
    ],
    addedDate: new Date('2024-04-15'),
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    isbn: '978-0307949486',
    publishedYear: 2005,
    genre: 'Mystery',
    availableCopies: 3,
    totalCopies: 4,
    borrowHistory: [
      {
        borrowerName: 'Gary Powell',
        borrowDate: new Date('2024-10-15'),
        returnDate: new Date('2024-11-05'),
        status: 'returned',
      },
      {
        borrowerName: 'Laura Brooks',
        borrowDate: new Date('2024-12-02'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 4,
        review: 'Gripping mystery with complex characters.',
        reviewDate: new Date('2024-11-08'),
      },
      {
        rating: 5,
        review: 'Intense and brilliantly plotted.',
        reviewDate: new Date('2024-11-20'),
      },
    ],
    addedDate: new Date('2024-05-01'),
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    isbn: '978-0399590504',
    publishedYear: 2018,
    genre: 'Biography',
    availableCopies: 1,
    totalCopies: 2,
    borrowHistory: [
      {
        borrowerName: 'Christine Murphy',
        borrowDate: new Date('2024-11-15'),
        returnDate: null,
        status: 'borrowed',
      },
    ],
    ratings: [
      {
        rating: 5,
        review: 'Powerful memoir about the transformative power of education.',
        reviewDate: new Date('2024-11-01'),
      },
    ],
    addedDate: new Date('2024-05-15'),
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    isbn: '978-0307387899',
    publishedYear: 2006,
    genre: 'Fiction',
    availableCopies: 2,
    totalCopies: 2,
    borrowHistory: [],
    ratings: [
      {
        rating: 4,
        review: 'Bleak but beautifully written. A haunting father-son story.',
        reviewDate: new Date('2024-09-15'),
      },
    ],
    addedDate: new Date('2024-06-01'),
  },
  {
    title: 'Becoming',
    author: 'Michelle Obama',
    isbn: '978-1524763138',
    publishedYear: 2018,
    genre: 'Biography',
    availableCopies: 3,
    totalCopies: 3,
    borrowHistory: [],
    ratings: [
      {
        rating: 5,
        review: "Inspiring and honest. Michelle Obama's story is remarkable.",
        reviewDate: new Date('2024-10-01'),
      },
      {
        rating: 5,
        review: 'A must-read biography. So well written!',
        reviewDate: new Date('2024-10-25'),
      },
    ],
    addedDate: new Date('2024-06-15'),
  },
])
